// comment

module test_msgs {
  module msg {
    @verbatim(language="comment", text=
      " comment for struct" "\n"
      " newline")
    struct StandAlone {
      @verbatim (language="comment", text=
        " comment for member 1")
      boolean data1;

      @verbatim (language="comment", text=
        " comment for member 2")
      @default (value=0)
      int32 data2;

      @default (value=0.0)
      float data3;

      @default (value="hello")
      string data4;

      @verbatim (language="comment", text=
        " comment for array member 1")
      sequence<int32> array1;

      @default (value="(-1, 0, 1)")
      sequence<int32> array2;

      @default (value="('aa', 'bb')")
      sequence<string> array3;

    };
  };
};
