name: main

on:
  push:
    branches:
      - main

jobs:
  markdown:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Markdown link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros: foxy
          - ros: galactic
          - ros: rolling

    runs-on: ${{ matrix.ros }}
    env:
      ROS_DISTRO: ${{ matrix.ros }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest
      - name: Run build
        run: |
          rdmd script/build
      - name: Run test
        run: |
          rdmd script/test
      - name: Build example
        run: |
          . /opt/ros/$ROS_DISTRO/setup.sh
          rdmd example/build
  deploy-pages:
    needs: test
    runs-on: rolling
    env:
      ROS_DISTRO: rolling
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest
      - name: Generate docs
        run: |
          rdmd script/gendoc
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allow_empty_commit: false
          publish_dir: docs
          user_name: GitHub Actions Bot
          user_email: <>