name: workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  markdown:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Markdown link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros: foxy
          - ros: galactic
          - ros: rolling
          - ros: humble

    runs-on: ${{ matrix.ros }}
    env:
      ROS_DISTRO: ${{ matrix.ros }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest
      - name: Run build
        run: |
          rdmd script/build
      - name: Run test
        run: |
          rdmd script/test
      - name: Build example
        run: |
          . /opt/ros/$ROS_DISTRO/setup.sh
          rdmd example/build

