name: workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  markdown:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Markdown link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
  test:
    runs-on: [self-hosted, foxy]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest
      - uses: sergeysova/jq-action@v2
      - name: Run build
        run: |
          . /opt/ros/foxy/setup.bash
          bash example/test/build_all.sh
      - name: Run tests
        run: |
          dub test :msg_gen
